spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-admin-password: 123456
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: li.haomin.whale.dialect.SQLiteDialect

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:whale.db
    username: admin
    password: 123456