spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    database-platform: li.haomin.whale.dialect.SQLiteDialect

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:F:\Projects\whale\whale-api\whale.db

logging:
  file:
    path: .
